name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MameSelector/MameSelector.csproj
      
    - name: Build
      run: dotnet build MameSelector/MameSelector.csproj --configuration Release --no-restore
      
    - name: Test (if tests exist)
      run: dotnet test MameSelector/MameSelector.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish Windows executable
      run: dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish/win-x64
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mame-rom-selector-windows
        path: ./publish/win-x64/

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: mame-rom-selector-windows
        path: ./artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: MAME ROM Selector v${{ github.run_number }}
        body: |
          ## MAME ROM Selector v${{ github.run_number }}
          
          ### Changes in this release:
          - Automated build from commit ${{ github.sha }}
          - Built for Windows
          
          ### Download:
          - **Windows**: Download `MameSelector.exe`
          
          ### Installation:
          1. Download the Windows executable
          2. Run `MameSelector.exe`
          
          ### Requirements:
          - .NET 8.0 Runtime (included in self-contained build)
          - Windows 10/11
        files: ./artifacts/MameSelector.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
