name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MameSelector/MameSelector.csproj
      
    - name: Build
      run: dotnet build MameSelector/MameSelector.csproj --configuration Release --no-restore
      
    - name: Test (if tests exist)
      run: dotnet test MameSelector/MameSelector.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish Windows executable
      run: dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish/win-x64
      
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mame-rom-selector-windows
        path: ./publish/win-x64/

