name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.3.3)'
        required: true
        default: 'v0.3.3'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'Bug fixes and improvements'

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build Windows
      run: dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish/win-x64
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: MAME ROM Selector ${{ github.event.inputs.version }}
        body: |
          ## MAME ROM Selector ${{ github.event.inputs.version }}
          
          ${{ github.event.inputs.release_notes }}
          
          ### Download:
          - **Windows**: Download `MameSelector.exe`
          
          ### Installation:
          1. Download the Windows executable
          2. Run `MameSelector.exe`
          
          ### Requirements:
          - .NET 8.0 Runtime (included in self-contained build)
          - Windows 10/11
        files: ./publish/win-x64/MameSelector.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
