name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'Bug fixes and improvements'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build Windows
      run: |
        dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish/win-x64
        
    - name: Build Linux
      run: |
        dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime linux-x64 --self-contained true --output ./publish/linux-x64
        
    - name: Build macOS
      run: |
        dotnet publish MameSelector/MameSelector.csproj --configuration Release --runtime osx-x64 --self-contained true --output ./publish/osx-x64
        
    - name: Create Windows ZIP
      run: |
        cd publish
        zip -r ../mame-rom-selector-windows.zip win-x64/
        
    - name: Create Linux ZIP
      run: |
        cd publish
        zip -r ../mame-rom-selector-linux.zip linux-x64/
        
    - name: Create macOS ZIP
      run: |
        cd publish
        zip -r ../mame-rom-selector-macos.zip osx-x64/
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: MAME ROM Selector ${{ github.event.inputs.version }}
        body: |
          ## MAME ROM Selector ${{ github.event.inputs.version }}
          
          ${{ github.event.inputs.release_notes }}
          
          ### Downloads:
          - **Windows**: Download `mame-rom-selector-windows.zip`
          - **Linux**: Download `mame-rom-selector-linux.zip`  
          - **macOS**: Download `mame-rom-selector-macos.zip`
          
          ### Installation:
          1. Download the appropriate archive for your platform
          2. Extract the files
          3. Run `MameSelector.exe` (Windows) or `MameSelector` (Linux/macOS)
          
          ### Requirements:
          - .NET 8.0 Runtime (included in self-contained builds)
          - Windows 10/11, Ubuntu 18.04+, or macOS 10.15+
        draft: false
        prerelease: false
        
    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mame-rom-selector-windows.zip
        asset_name: mame-rom-selector-windows.zip
        asset_content_type: application/zip
        
    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mame-rom-selector-linux.zip
        asset_name: mame-rom-selector-linux.zip
        asset_content_type: application/zip
        
    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mame-rom-selector-macos.zip
        asset_name: mame-rom-selector-macos.zip
        asset_content_type: application/zip
